import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import math
import os

# --- TRADUCCIONES Y PALETAS (Diseño Streamlit) ---
CAT_TRANS = {
    "Antropogénico": "Anthropogenic", "Mamífero": "Mammal", 
    "Anfibio": "Amphibian", "Insecto": "Insect", "Ave": "Bird"
}
PERIOD_TRANS = {
    "Amanecer Crítico": "Dawn", "Anochecer Crítico": "Dusk"
}
# Usaremos "viridis" o "magma" como en tu dashboard para mantener consistencia
PALETTE = "viridis" 

json_data = '''

{
	"table": "clips",
	"rows":
	[
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 3.62,
			"porcentaje_sd": 3.81,
			"porcentaje_min": 0.57,
			"porcentaje_max": 10.81,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 19.84,
			"porcentaje_sd": 11.99,
			"porcentaje_min": 6.3,
			"porcentaje_max": 39.74,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 41.0,
			"porcentaje_sd": 14.84,
			"porcentaje_min": 17.57,
			"porcentaje_max": 57.71,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 35.3,
			"porcentaje_sd": 13.38,
			"porcentaje_min": 16.57,
			"porcentaje_max": 49.29,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.56,
			"porcentaje_sd": 0.12,
			"porcentaje_min": 0.44,
			"porcentaje_max": 0.68,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 1.77,
			"porcentaje_sd": 1.4,
			"porcentaje_min": 0.4,
			"porcentaje_max": 3.83,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 15.79,
			"porcentaje_sd": 9.86,
			"porcentaje_min": 2.58,
			"porcentaje_max": 29.81,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 26.86,
			"porcentaje_sd": 9.71,
			"porcentaje_min": 11.0,
			"porcentaje_max": 39.02,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 55.71,
			"porcentaje_sd": 15.46,
			"porcentaje_min": 36.6,
			"porcentaje_max": 75.6,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.87,
			"porcentaje_sd": 0.53,
			"porcentaje_min": 0.48,
			"porcentaje_max": 1.48,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 1.83,
			"porcentaje_sd": 1.09,
			"porcentaje_min": 0.32,
			"porcentaje_max": 2.79,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 1.84,
			"porcentaje_sd": 2.13,
			"porcentaje_min": 0.51,
			"porcentaje_max": 6.46,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 6.84,
			"porcentaje_sd": 6.77,
			"porcentaje_min": 1.08,
			"porcentaje_max": 17.98,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 3.33,
			"porcentaje_sd": 1.57,
			"porcentaje_min": 2.22,
			"porcentaje_max": 4.44,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 29.41,
			"porcentaje_sd": 27.44,
			"porcentaje_min": 2.6,
			"porcentaje_max": 92.31,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 7.32,
			"porcentaje_sd": 3.46,
			"porcentaje_min": 1.21,
			"porcentaje_max": 11.26,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 22.16,
			"porcentaje_sd": 10.18,
			"porcentaje_min": 8.99,
			"porcentaje_max": 36.18,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 6.39,
			"porcentaje_sd": 3.54,
			"porcentaje_min": 3.89,
			"porcentaje_max": 8.89,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 44.43,
			"porcentaje_sd": 21.52,
			"porcentaje_min": 19.33,
			"porcentaje_max": 76.16,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 28.26,
			"porcentaje_sd": 5.89,
			"porcentaje_min": 18.85,
			"porcentaje_max": 37.92,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 69.0,
			"porcentaje_sd": 7.12,
			"porcentaje_min": 57.06,
			"porcentaje_max": 79.3,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 93.52,
			"porcentaje_sd": 5.78,
			"porcentaje_min": 88.89,
			"porcentaje_max": 100.0,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 32.92,
			"porcentaje_sd": 18.43,
			"porcentaje_min": 7.69,
			"porcentaje_max": 72.73,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 62.57,
			"porcentaje_sd": 7.12,
			"porcentaje_min": 50.13,
			"porcentaje_max": 72.22,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.6,
			"porcentaje_sd": 0.35,
			"porcentaje_min": 0.28,
			"porcentaje_max": 1.08,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 100.0,
			"porcentaje_sd": null,
			"porcentaje_min": 100.0,
			"porcentaje_max": 100.0,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 1.27,
			"porcentaje_sd": 0.5,
			"porcentaje_min": 0.66,
			"porcentaje_max": 2.04,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 7.71,
			"porcentaje_sd": 6.33,
			"porcentaje_min": 0.68,
			"porcentaje_max": 15.04,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 36.6,
			"porcentaje_sd": 16.51,
			"porcentaje_min": 23.16,
			"porcentaje_max": 55.03,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 29.32,
			"porcentaje_sd": 24.77,
			"porcentaje_min": 0.6,
			"porcentaje_max": 50.0,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 11.31,
			"porcentaje_sd": 5.47,
			"porcentaje_min": 6.53,
			"porcentaje_max": 22.49,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 37.59,
			"porcentaje_sd": 31.67,
			"porcentaje_min": 7.49,
			"porcentaje_max": 100.0,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 40.12,
			"porcentaje_sd": 40.83,
			"porcentaje_min": 11.86,
			"porcentaje_max": 100.0,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 53.32,
			"porcentaje_sd": 22.64,
			"porcentaje_min": 22.22,
			"porcentaje_max": 100.0,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 3.3,
			"porcentaje_sd": 1.71,
			"porcentaje_min": 1.34,
			"porcentaje_max": 5.46,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 4.33,
			"porcentaje_sd": 3.56,
			"porcentaje_min": 0.31,
			"porcentaje_max": 11.78,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 9.6,
			"porcentaje_sd": null,
			"porcentaje_min": 9.6,
			"porcentaje_max": 9.6,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 20.63,
			"porcentaje_sd": 28.8,
			"porcentaje_min": 4.78,
			"porcentaje_max": 100.0,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 2.77,
			"porcentaje_sd": 1.86,
			"porcentaje_min": 0.41,
			"porcentaje_max": 5.53,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 59.28,
			"porcentaje_sd": 21.49,
			"porcentaje_min": 14.78,
			"porcentaje_max": 80.5,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 55.03,
			"porcentaje_sd": 35.58,
			"porcentaje_min": 13.02,
			"porcentaje_max": 100.0,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 33.36,
			"porcentaje_sd": 13.87,
			"porcentaje_min": 19.31,
			"porcentaje_max": 65.29,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 82.59,
			"porcentaje_sd": 5.78,
			"porcentaje_min": 70.42,
			"porcentaje_max": 87.14,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.74,
			"porcentaje_sd": 0.56,
			"porcentaje_min": 0.31,
			"porcentaje_max": 1.5,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2025,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 0.2,
			"porcentaje_sd": null,
			"porcentaje_min": 0.2,
			"porcentaje_max": 0.2,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 18.77,
			"porcentaje_sd": 12.97,
			"porcentaje_min": 1.75,
			"porcentaje_max": 33.33,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.87,
			"porcentaje_sd": 3.25,
			"porcentaje_min": 0.25,
			"porcentaje_max": 9.21,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.73,
			"porcentaje_sd": 0.77,
			"porcentaje_min": 0.18,
			"porcentaje_max": 1.28,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 0.27,
			"porcentaje_sd": 0.34,
			"porcentaje_min": 0.08,
			"porcentaje_max": 0.79,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 1.08,
			"porcentaje_sd": 1.66,
			"porcentaje_min": 0.09,
			"porcentaje_max": 3.55,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 39.83,
			"porcentaje_sd": 40.39,
			"porcentaje_min": 2.33,
			"porcentaje_max": 100.0,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 28.36,
			"porcentaje_sd": 36.92,
			"porcentaje_min": 1.21,
			"porcentaje_max": 100.0,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 12.87,
			"porcentaje_sd": 14.67,
			"porcentaje_min": 1.94,
			"porcentaje_max": 33.33,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 31.73,
			"porcentaje_sd": 39.35,
			"porcentaje_min": 0.79,
			"porcentaje_max": 100.0,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 33.45,
			"porcentaje_sd": 16.75,
			"porcentaje_min": 8.38,
			"porcentaje_max": 58.89,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 34.53,
			"porcentaje_sd": 13.64,
			"porcentaje_min": 10.47,
			"porcentaje_max": 50.88,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 30.57,
			"porcentaje_sd": 16.86,
			"porcentaje_min": 7.09,
			"porcentaje_max": 65.41,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 41.57,
			"porcentaje_sd": 23.54,
			"porcentaje_min": 16.12,
			"porcentaje_max": 66.67,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 48.73,
			"porcentaje_sd": 33.6,
			"porcentaje_min": 1.87,
			"porcentaje_max": 90.83,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 27.86,
			"porcentaje_sd": 14.22,
			"porcentaje_min": 4.21,
			"porcentaje_max": 50.0,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 49.66,
			"porcentaje_sd": 19.68,
			"porcentaje_min": 33.33,
			"porcentaje_max": 87.21,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 57.09,
			"porcentaje_sd": 15.74,
			"porcentaje_min": 31.12,
			"porcentaje_max": 87.4,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 59.71,
			"porcentaje_sd": 20.64,
			"porcentaje_min": 33.33,
			"porcentaje_max": 81.94,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 35.93,
			"porcentaje_sd": 34.07,
			"porcentaje_min": 4.1,
			"porcentaje_max": 95.6,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 39.79,
			"porcentaje_sd": 20.6,
			"porcentaje_min": 16.14,
			"porcentaje_max": 76.84,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 1.09,
			"porcentaje_sd": null,
			"porcentaje_min": 1.09,
			"porcentaje_max": 1.09,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 0.18,
			"porcentaje_sd": 0.17,
			"porcentaje_min": 0.08,
			"porcentaje_max": 0.38,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.37,
			"porcentaje_sd": null,
			"porcentaje_min": 0.37,
			"porcentaje_max": 0.37,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 1.3,
			"porcentaje_sd": 0.54,
			"porcentaje_min": 0.8,
			"porcentaje_max": 2.19,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 11.22,
			"porcentaje_sd": 29.51,
			"porcentaje_min": 0.66,
			"porcentaje_max": 100.0,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 2.03,
			"porcentaje_sd": 3.26,
			"porcentaje_min": 0.09,
			"porcentaje_max": 7.79,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 16.25,
			"porcentaje_sd": 12.98,
			"porcentaje_min": 2.75,
			"porcentaje_max": 31.17,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.95,
			"porcentaje_sd": 0.67,
			"porcentaje_min": 0.47,
			"porcentaje_max": 1.42,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 17.5,
			"porcentaje_sd": 22.85,
			"porcentaje_min": 0.16,
			"porcentaje_max": 50.0,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 7.78,
			"porcentaje_sd": 15.72,
			"porcentaje_min": 0.37,
			"porcentaje_max": 50.0,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 64.82,
			"porcentaje_sd": 43.43,
			"porcentaje_min": 6.49,
			"porcentaje_max": 100.0,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 19.15,
			"porcentaje_sd": 28.96,
			"porcentaje_min": 0.15,
			"porcentaje_max": 100.0,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 55.0,
			"porcentaje_sd": 40.55,
			"porcentaje_min": 3.34,
			"porcentaje_max": 100.0,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 34.2,
			"porcentaje_sd": 33.38,
			"porcentaje_min": 3.23,
			"porcentaje_max": 100.0,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 49.17,
			"porcentaje_sd": 23.68,
			"porcentaje_min": 2.93,
			"porcentaje_max": 100.0,
			"dias_muestreados": 14
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 32.98,
			"porcentaje_sd": 11.82,
			"porcentaje_min": 19.83,
			"porcentaje_max": 42.74,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 13.18,
			"porcentaje_sd": 13.28,
			"porcentaje_min": 0.15,
			"porcentaje_max": 38.28,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 10.71,
			"porcentaje_sd": 9.54,
			"porcentaje_min": 5.33,
			"porcentaje_max": 25.0,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 12.67,
			"porcentaje_sd": 14.35,
			"porcentaje_min": 0.1,
			"porcentaje_max": 42.68,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 9.21,
			"porcentaje_sd": 11.1,
			"porcentaje_min": 0.09,
			"porcentaje_max": 33.33,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 48.84,
			"porcentaje_sd": 31.82,
			"porcentaje_min": 4.82,
			"porcentaje_max": 85.13,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 67.64,
			"porcentaje_sd": 21.6,
			"porcentaje_min": 14.66,
			"porcentaje_max": 96.95,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 67.47,
			"porcentaje_sd": 25.61,
			"porcentaje_min": 40.0,
			"porcentaje_max": 90.04,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 64.92,
			"porcentaje_sd": 24.61,
			"porcentaje_min": 15.69,
			"porcentaje_max": 100.0,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 47.62,
			"porcentaje_sd": 22.96,
			"porcentaje_min": 19.56,
			"porcentaje_max": 96.23,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.85,
			"porcentaje_sd": null,
			"porcentaje_min": 0.85,
			"porcentaje_max": 0.85,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.21,
			"porcentaje_sd": 0.2,
			"porcentaje_min": 0.07,
			"porcentaje_max": 0.36,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.86,
			"porcentaje_sd": 0.89,
			"porcentaje_min": 0.12,
			"porcentaje_max": 1.85,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 8.26,
			"porcentaje_sd": 10.8,
			"porcentaje_min": 1.49,
			"porcentaje_max": 27.27,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 2.91,
			"porcentaje_sd": 1.99,
			"porcentaje_min": 1.13,
			"porcentaje_max": 6.32,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 1.47,
			"porcentaje_sd": 0.61,
			"porcentaje_min": 0.62,
			"porcentaje_max": 2.15,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 3.33,
			"porcentaje_sd": 4.3,
			"porcentaje_min": 0.53,
			"porcentaje_max": 12.38,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 5.21,
			"porcentaje_sd": 7.15,
			"porcentaje_min": 0.83,
			"porcentaje_max": 23.08,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 11.78,
			"porcentaje_sd": 13.97,
			"porcentaje_min": 0.54,
			"porcentaje_max": 31.52,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 20.77,
			"porcentaje_sd": 5.03,
			"porcentaje_min": 13.44,
			"porcentaje_max": 26.98,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 20.21,
			"porcentaje_sd": 15.81,
			"porcentaje_min": 2.4,
			"porcentaje_max": 57.48,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 35.17,
			"porcentaje_sd": 31.1,
			"porcentaje_min": 5.06,
			"porcentaje_max": 100.0,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 14.47,
			"porcentaje_sd": 15.62,
			"porcentaje_min": 0.63,
			"porcentaje_max": 55.28,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 42.57,
			"porcentaje_sd": 12.26,
			"porcentaje_min": 31.88,
			"porcentaje_max": 68.22,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 38.45,
			"porcentaje_sd": 6.5,
			"porcentaje_min": 29.54,
			"porcentaje_max": 49.34,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 18.03,
			"porcentaje_sd": 15.62,
			"porcentaje_min": 0.95,
			"porcentaje_max": 43.75,
			"dias_muestreados": 14
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 21.96,
			"porcentaje_sd": 12.28,
			"porcentaje_min": 7.16,
			"porcentaje_max": 49.37,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 37.91,
			"porcentaje_sd": 29.29,
			"porcentaje_min": 1.75,
			"porcentaje_max": 90.67,
			"dias_muestreados": 21
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 37.56,
			"porcentaje_sd": 19.29,
			"porcentaje_min": 0.78,
			"porcentaje_max": 59.7,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 37.0,
			"porcentaje_sd": 9.56,
			"porcentaje_min": 24.58,
			"porcentaje_max": 47.68,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 63.66,
			"porcentaje_sd": 27.25,
			"porcentaje_min": 28.91,
			"porcentaje_max": 99.05,
			"dias_muestreados": 14
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 52.9,
			"porcentaje_sd": 8.93,
			"porcentaje_min": 39.68,
			"porcentaje_max": 64.96,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 45.97,
			"porcentaje_sd": 27.22,
			"porcentaje_min": 3.75,
			"porcentaje_max": 91.06,
			"dias_muestreados": 21
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 15.33,
			"porcentaje_sd": null,
			"porcentaje_min": 15.33,
			"porcentaje_max": 15.33,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.21,
			"porcentaje_sd": 0.94,
			"porcentaje_min": 0.41,
			"porcentaje_max": 2.38,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 1.62,
			"porcentaje_sd": 0.7,
			"porcentaje_min": 0.78,
			"porcentaje_max": 2.48,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 1.37,
			"porcentaje_sd": 0.08,
			"porcentaje_min": 1.32,
			"porcentaje_max": 1.43,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 4.14,
			"porcentaje_sd": 2.37,
			"porcentaje_min": 1.33,
			"porcentaje_max": 8.75,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 4.76,
			"porcentaje_sd": 3.54,
			"porcentaje_min": 0.47,
			"porcentaje_max": 10.59,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 9.05,
			"porcentaje_sd": 6.19,
			"porcentaje_min": 1.54,
			"porcentaje_max": 18.66,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 20.89,
			"porcentaje_sd": 16.26,
			"porcentaje_min": 2.28,
			"porcentaje_max": 47.16,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 4.93,
			"porcentaje_sd": 6.53,
			"porcentaje_min": 0.47,
			"porcentaje_max": 19.79,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 8.71,
			"porcentaje_sd": 9.59,
			"porcentaje_min": 0.86,
			"porcentaje_max": 29.29,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 10.41,
			"porcentaje_sd": 6.96,
			"porcentaje_min": 1.18,
			"porcentaje_max": 21.5,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 21.02,
			"porcentaje_sd": 8.42,
			"porcentaje_min": 5.97,
			"porcentaje_max": 31.87,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 42.2,
			"porcentaje_sd": 22.82,
			"porcentaje_min": 3.41,
			"porcentaje_max": 100.0,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 37.21,
			"porcentaje_sd": 28.58,
			"porcentaje_min": 8.92,
			"porcentaje_max": 100.0,
			"dias_muestreados": 14
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 23.06,
			"porcentaje_sd": 20.86,
			"porcentaje_min": 2.52,
			"porcentaje_max": 86.24,
			"dias_muestreados": 21
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 10.74,
			"porcentaje_sd": 5.6,
			"porcentaje_min": 1.84,
			"porcentaje_max": 19.64,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 9.8,
			"porcentaje_sd": 7.95,
			"porcentaje_min": 1.01,
			"porcentaje_max": 27.44,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 17.53,
			"porcentaje_sd": 26.81,
			"porcentaje_min": 3.1,
			"porcentaje_max": 100.0,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 16.06,
			"porcentaje_sd": 17.54,
			"porcentaje_min": 1.29,
			"porcentaje_max": 66.67,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 31.42,
			"porcentaje_sd": 26.91,
			"porcentaje_min": 0.59,
			"porcentaje_max": 80.77,
			"dias_muestreados": 20
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 73.63,
			"porcentaje_sd": 8.79,
			"porcentaje_min": 62.62,
			"porcentaje_max": 88.96,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 59.68,
			"porcentaje_sd": 11.16,
			"porcentaje_min": 38.99,
			"porcentaje_max": 78.28,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 31.98,
			"porcentaje_sd": 13.74,
			"porcentaje_min": 3.27,
			"porcentaje_max": 47.08,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 59.38,
			"porcentaje_sd": 16.17,
			"porcentaje_min": 33.91,
			"porcentaje_max": 86.57,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 43.52,
			"porcentaje_sd": 25.96,
			"porcentaje_min": 4.24,
			"porcentaje_max": 91.39,
			"dias_muestreados": 19
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 1.24,
			"porcentaje_sd": 0.65,
			"porcentaje_min": 0.68,
			"porcentaje_max": 1.94,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.8,
			"porcentaje_sd": 0.44,
			"porcentaje_min": 1.49,
			"porcentaje_max": 2.11,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 1.65,
			"porcentaje_sd": 1.07,
			"porcentaje_min": 0.57,
			"porcentaje_max": 2.92,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2024,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 1.76,
			"porcentaje_sd": 1.38,
			"porcentaje_min": 0.32,
			"porcentaje_max": 4.35,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 5.52,
			"porcentaje_sd": 6.05,
			"porcentaje_min": 0.44,
			"porcentaje_max": 18.47,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 1.12,
			"porcentaje_sd": 1.41,
			"porcentaje_min": 0.15,
			"porcentaje_max": 4.8,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 4.06,
			"porcentaje_sd": 4.96,
			"porcentaje_min": 0.83,
			"porcentaje_max": 18.25,
			"dias_muestreados": 12
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.7,
			"porcentaje_sd": 0.45,
			"porcentaje_min": 0.17,
			"porcentaje_max": 1.21,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 9.27,
			"porcentaje_sd": 12.02,
			"porcentaje_min": 0.67,
			"porcentaje_max": 33.33,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 13.04,
			"porcentaje_sd": 8.48,
			"porcentaje_min": 0.47,
			"porcentaje_max": 25.13,
			"dias_muestreados": 15
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 5.19,
			"porcentaje_sd": 6.48,
			"porcentaje_min": 0.55,
			"porcentaje_max": 26.7,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 9.25,
			"porcentaje_sd": 6.29,
			"porcentaje_min": 0.79,
			"porcentaje_max": 20.69,
			"dias_muestreados": 15
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 22.71,
			"porcentaje_sd": 5.61,
			"porcentaje_min": 14.74,
			"porcentaje_max": 32.93,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 17.54,
			"porcentaje_sd": 3.59,
			"porcentaje_min": 10.96,
			"porcentaje_max": 21.28,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 15.53,
			"porcentaje_sd": 13.09,
			"porcentaje_min": 2.55,
			"porcentaje_max": 50.57,
			"dias_muestreados": 16
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 33.35,
			"porcentaje_sd": 13.9,
			"porcentaje_min": 18.6,
			"porcentaje_max": 67.07,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 20.56,
			"porcentaje_sd": 9.17,
			"porcentaje_min": 3.45,
			"porcentaje_max": 34.12,
			"dias_muestreados": 16
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 29.79,
			"porcentaje_sd": 5.32,
			"porcentaje_min": 22.2,
			"porcentaje_max": 40.17,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 33.05,
			"porcentaje_sd": 3.68,
			"porcentaje_min": 27.54,
			"porcentaje_max": 38.8,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 68.8,
			"porcentaje_sd": 20.49,
			"porcentaje_min": 33.1,
			"porcentaje_max": 96.94,
			"dias_muestreados": 16
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 60.53,
			"porcentaje_sd": 14.44,
			"porcentaje_min": 28.92,
			"porcentaje_max": 78.6,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 67.4,
			"porcentaje_sd": 11.55,
			"porcentaje_min": 42.65,
			"porcentaje_max": 88.78,
			"dias_muestreados": 16
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 46.22,
			"porcentaje_sd": 7.05,
			"porcentaje_min": 35.59,
			"porcentaje_max": 57.99,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 39.64,
			"porcentaje_sd": 8.87,
			"porcentaje_min": 23.25,
			"porcentaje_max": 49.46,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 1.11,
			"porcentaje_sd": 1.23,
			"porcentaje_min": 0.26,
			"porcentaje_max": 3.21,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.6,
			"porcentaje_sd": 0.63,
			"porcentaje_min": 0.15,
			"porcentaje_max": 1.04,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.02,
			"porcentaje_sd": 0.53,
			"porcentaje_min": 0.34,
			"porcentaje_max": 1.67,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.98,
			"porcentaje_sd": 1.03,
			"porcentaje_min": 0.16,
			"porcentaje_max": 2.26,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 0.5,
			"porcentaje_sd": 0.3,
			"porcentaje_min": 0.17,
			"porcentaje_max": 0.93,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 6.75,
			"porcentaje_sd": 4.72,
			"porcentaje_min": 0.6,
			"porcentaje_max": 16.41,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 6.3,
			"porcentaje_sd": 3.93,
			"porcentaje_min": 0.4,
			"porcentaje_max": 13.11,
			"dias_muestreados": 18
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 6.23,
			"porcentaje_sd": 15.01,
			"porcentaje_min": 0.37,
			"porcentaje_max": 56.0,
			"dias_muestreados": 13
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 4.93,
			"porcentaje_sd": 4.32,
			"porcentaje_min": 1.04,
			"porcentaje_max": 14.06,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 12.46,
			"porcentaje_sd": 8.65,
			"porcentaje_min": 2.92,
			"porcentaje_max": 26.94,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 11.32,
			"porcentaje_sd": 8.0,
			"porcentaje_min": 1.98,
			"porcentaje_max": 32.24,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 12.64,
			"porcentaje_sd": 20.7,
			"porcentaje_min": 0.35,
			"porcentaje_max": 92.74,
			"dias_muestreados": 18
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 23.24,
			"porcentaje_sd": 16.81,
			"porcentaje_min": 2.93,
			"porcentaje_max": 68.13,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 35.83,
			"porcentaje_sd": 23.48,
			"porcentaje_min": 22.4,
			"porcentaje_max": 100.0,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 34.71,
			"porcentaje_sd": 6.76,
			"porcentaje_min": 25.91,
			"porcentaje_max": 43.73,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 10.83,
			"porcentaje_sd": 10.68,
			"porcentaje_min": 0.42,
			"porcentaje_max": 33.96,
			"dias_muestreados": 18
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 13.35,
			"porcentaje_sd": 7.76,
			"porcentaje_min": 3.23,
			"porcentaje_max": 29.43,
			"dias_muestreados": 18
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 14.49,
			"porcentaje_sd": 12.56,
			"porcentaje_min": 0.39,
			"porcentaje_max": 40.59,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 29.66,
			"porcentaje_sd": 7.56,
			"porcentaje_min": 21.69,
			"porcentaje_max": 40.76,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 14.44,
			"porcentaje_sd": 6.15,
			"porcentaje_min": 3.11,
			"porcentaje_max": 19.63,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 72.08,
			"porcentaje_sd": 16.89,
			"porcentaje_min": 39.32,
			"porcentaje_max": 93.7,
			"dias_muestreados": 18
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 71.63,
			"porcentaje_sd": 9.17,
			"porcentaje_min": 50.51,
			"porcentaje_max": 89.02,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 57.24,
			"porcentaje_sd": 20.19,
			"porcentaje_min": 15.0,
			"porcentaje_max": 85.03,
			"dias_muestreados": 17
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 36.52,
			"porcentaje_sd": 11.07,
			"porcentaje_min": 23.22,
			"porcentaje_max": 52.2,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 37.58,
			"porcentaje_sd": 6.51,
			"porcentaje_min": 29.87,
			"porcentaje_max": 46.01,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.23,
			"porcentaje_sd": null,
			"porcentaje_min": 0.23,
			"porcentaje_max": 0.23,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.32,
			"porcentaje_sd": 0.28,
			"porcentaje_min": 0.16,
			"porcentaje_max": 0.64,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 0.77,
			"porcentaje_sd": 0.4,
			"porcentaje_min": 0.33,
			"porcentaje_max": 1.38,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.34,
			"porcentaje_sd": 0.16,
			"porcentaje_min": 0.17,
			"porcentaje_max": 0.52,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 1.23,
			"porcentaje_sd": 1.03,
			"porcentaje_min": 0.43,
			"porcentaje_max": 2.7,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.63,
			"porcentaje_sd": 0.34,
			"porcentaje_min": 0.47,
			"porcentaje_max": 1.32,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.24,
			"porcentaje_sd": null,
			"porcentaje_min": 0.24,
			"porcentaje_max": 0.24,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 1.42,
			"porcentaje_sd": 0.99,
			"porcentaje_min": 0.17,
			"porcentaje_max": 2.63,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.57,
			"porcentaje_sd": 1.58,
			"porcentaje_min": 0.45,
			"porcentaje_max": 4.3,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.92,
			"porcentaje_sd": null,
			"porcentaje_min": 0.92,
			"porcentaje_max": 0.92,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 2.07,
			"porcentaje_sd": 2.75,
			"porcentaje_min": 0.15,
			"porcentaje_max": 6.82,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 1.23,
			"porcentaje_sd": 1.04,
			"porcentaje_min": 0.24,
			"porcentaje_max": 3.22,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 4.83,
			"porcentaje_sd": 2.24,
			"porcentaje_min": 2.66,
			"porcentaje_max": 7.44,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "cahuide",
			"porcentaje_promedio": 0.85,
			"porcentaje_sd": 0.72,
			"porcentaje_min": 0.3,
			"porcentaje_max": 2.1,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 12.58,
			"porcentaje_sd": 9.82,
			"porcentaje_min": 4.81,
			"porcentaje_max": 31.52,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 12.47,
			"porcentaje_sd": 6.45,
			"porcentaje_min": 5.28,
			"porcentaje_max": 17.75,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 25.55,
			"porcentaje_sd": 6.07,
			"porcentaje_min": 18.89,
			"porcentaje_max": 36.68,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 15.32,
			"porcentaje_sd": 2.2,
			"porcentaje_min": 12.75,
			"porcentaje_max": 18.01,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 13.86,
			"porcentaje_sd": 5.14,
			"porcentaje_min": 4.76,
			"porcentaje_max": 20.23,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 9.97,
			"porcentaje_sd": 6.04,
			"porcentaje_min": 0.68,
			"porcentaje_max": 17.05,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 5.46,
			"porcentaje_sd": 1.36,
			"porcentaje_min": 3.39,
			"porcentaje_max": 8.18,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 13.17,
			"porcentaje_sd": 3.33,
			"porcentaje_min": 8.08,
			"porcentaje_max": 17.21,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "cahuide",
			"porcentaje_promedio": 28.04,
			"porcentaje_sd": 5.31,
			"porcentaje_min": 21.22,
			"porcentaje_max": 35.34,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 22.35,
			"porcentaje_sd": 8.85,
			"porcentaje_min": 11.36,
			"porcentaje_max": 37.11,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 7.97,
			"porcentaje_sd": 5.7,
			"porcentaje_min": 3.52,
			"porcentaje_max": 14.39,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 14.62,
			"porcentaje_sd": 3.34,
			"porcentaje_min": 10.15,
			"porcentaje_max": 18.72,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 28.41,
			"porcentaje_sd": 4.75,
			"porcentaje_min": 23.68,
			"porcentaje_max": 35.68,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 30.27,
			"porcentaje_sd": 10.4,
			"porcentaje_min": 15.87,
			"porcentaje_max": 40.28,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 17.29,
			"porcentaje_sd": 5.41,
			"porcentaje_min": 7.43,
			"porcentaje_max": 23.33,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 42.92,
			"porcentaje_sd": 5.85,
			"porcentaje_min": 36.29,
			"porcentaje_max": 54.86,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 29.38,
			"porcentaje_sd": 5.94,
			"porcentaje_min": 20.09,
			"porcentaje_max": 37.19,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "cahuide",
			"porcentaje_promedio": 26.48,
			"porcentaje_sd": 5.59,
			"porcentaje_min": 20.76,
			"porcentaje_max": 33.46,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 64.04,
			"porcentaje_sd": 12.07,
			"porcentaje_min": 48.8,
			"porcentaje_max": 82.05,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 79.48,
			"porcentaje_sd": 10.48,
			"porcentaje_min": 70.99,
			"porcentaje_max": 91.2,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 58.15,
			"porcentaje_sd": 7.16,
			"porcentaje_min": 45.89,
			"porcentaje_max": 66.89,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 54.93,
			"porcentaje_sd": 4.73,
			"porcentaje_min": 50.0,
			"porcentaje_max": 63.36,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 53.11,
			"porcentaje_sd": 11.06,
			"porcentaje_min": 43.4,
			"porcentaje_max": 73.81,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 70.5,
			"porcentaje_sd": 12.11,
			"porcentaje_min": 58.64,
			"porcentaje_max": 91.55,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 50.3,
			"porcentaje_sd": 5.85,
			"porcentaje_min": 39.15,
			"porcentaje_max": 59.01,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 53.18,
			"porcentaje_sd": 11.31,
			"porcentaje_min": 39.9,
			"porcentaje_max": 71.13,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "cahuide",
			"porcentaje_promedio": 43.21,
			"porcentaje_sd": 7.32,
			"porcentaje_min": 31.2,
			"porcentaje_max": 51.57,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.78,
			"porcentaje_sd": 0.53,
			"porcentaje_min": 0.48,
			"porcentaje_max": 1.4,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 0.51,
			"porcentaje_sd": 0.22,
			"porcentaje_min": 0.3,
			"porcentaje_max": 0.74,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 0.2,
			"porcentaje_sd": null,
			"porcentaje_min": 0.2,
			"porcentaje_max": 0.2,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 3.13,
			"porcentaje_sd": 2.03,
			"porcentaje_min": 1.04,
			"porcentaje_max": 5.56,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 0.26,
			"porcentaje_sd": 0.14,
			"porcentaje_min": 0.15,
			"porcentaje_max": 0.44,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 0.54,
			"porcentaje_sd": 0.36,
			"porcentaje_min": 0.22,
			"porcentaje_max": 0.91,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 1.06,
			"porcentaje_sd": 0.65,
			"porcentaje_min": 0.67,
			"porcentaje_max": 2.33,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "cahuide",
			"porcentaje_promedio": 1.88,
			"porcentaje_sd": 1.79,
			"porcentaje_min": 0.16,
			"porcentaje_max": 4.15,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.62,
			"porcentaje_sd": 0.37,
			"porcentaje_min": 0.16,
			"porcentaje_max": 1.06,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.25,
			"porcentaje_sd": 0.05,
			"porcentaje_min": 0.21,
			"porcentaje_max": 0.28,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 1.46,
			"porcentaje_sd": 2.56,
			"porcentaje_min": 0.24,
			"porcentaje_max": 6.67,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 6.52,
			"porcentaje_sd": 3.5,
			"porcentaje_min": 1.55,
			"porcentaje_max": 11.62,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 1.12,
			"porcentaje_sd": 1.05,
			"porcentaje_min": 0.38,
			"porcentaje_max": 1.87,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 1.8,
			"porcentaje_sd": 1.02,
			"porcentaje_min": 0.93,
			"porcentaje_max": 3.59,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 3.39,
			"porcentaje_sd": 2.52,
			"porcentaje_min": 0.22,
			"porcentaje_max": 7.48,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 1.86,
			"porcentaje_sd": 1.29,
			"porcentaje_min": 0.65,
			"porcentaje_max": 3.48,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "cahuide",
			"porcentaje_promedio": 2.48,
			"porcentaje_sd": 2.32,
			"porcentaje_min": 1.03,
			"porcentaje_max": 7.1,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 27.18,
			"porcentaje_sd": 12.38,
			"porcentaje_min": 12.54,
			"porcentaje_max": 44.68,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 15.82,
			"porcentaje_sd": 3.29,
			"porcentaje_min": 12.05,
			"porcentaje_max": 18.09,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 28.73,
			"porcentaje_sd": 6.65,
			"porcentaje_min": 17.8,
			"porcentaje_max": 36.99,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 20.94,
			"porcentaje_sd": 12.64,
			"porcentaje_min": 8.49,
			"porcentaje_max": 41.12,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 71.25,
			"porcentaje_sd": 21.16,
			"porcentaje_min": 45.64,
			"porcentaje_max": 100.0,
			"dias_muestreados": 7
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 38.47,
			"porcentaje_sd": 7.04,
			"porcentaje_min": 28.97,
			"porcentaje_max": 46.83,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 16.68,
			"porcentaje_sd": 7.72,
			"porcentaje_min": 8.21,
			"porcentaje_max": 35.15,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 52.42,
			"porcentaje_sd": 17.79,
			"porcentaje_min": 30.41,
			"porcentaje_max": 80.69,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "cahuide",
			"porcentaje_promedio": 39.99,
			"porcentaje_sd": 6.49,
			"porcentaje_min": 33.45,
			"porcentaje_max": 52.56,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 5.16,
			"porcentaje_sd": 2.73,
			"porcentaje_min": 1.43,
			"porcentaje_max": 8.33,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 4.42,
			"porcentaje_sd": 2.53,
			"porcentaje_min": 1.7,
			"porcentaje_max": 6.7,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 1.89,
			"porcentaje_sd": 0.97,
			"porcentaje_min": 0.52,
			"porcentaje_max": 3.26,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 7.0,
			"porcentaje_sd": 5.38,
			"porcentaje_min": 2.71,
			"porcentaje_max": 17.32,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 11.98,
			"porcentaje_sd": 5.14,
			"porcentaje_min": 2.34,
			"porcentaje_max": 17.72,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 6.77,
			"porcentaje_sd": 2.18,
			"porcentaje_min": 4.53,
			"porcentaje_max": 9.91,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 5.19,
			"porcentaje_sd": 2.39,
			"porcentaje_min": 2.24,
			"porcentaje_max": 9.5,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 8.01,
			"porcentaje_sd": 4.08,
			"porcentaje_min": 2.99,
			"porcentaje_max": 12.9,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "cahuide",
			"porcentaje_promedio": 6.1,
			"porcentaje_sd": 3.19,
			"porcentaje_min": 1.32,
			"porcentaje_max": 10.74,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 67.16,
			"porcentaje_sd": 13.88,
			"porcentaje_min": 45.39,
			"porcentaje_max": 80.49,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 79.45,
			"porcentaje_sd": 3.7,
			"porcentaje_min": 75.7,
			"porcentaje_max": 83.09,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "LLANCHAMA",
			"porcentaje_promedio": 67.91,
			"porcentaje_sd": 7.17,
			"porcentaje_min": 61.96,
			"porcentaje_max": 80.41,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 65.31,
			"porcentaje_sd": 12.05,
			"porcentaje_min": 47.72,
			"porcentaje_max": 80.91,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 25.37,
			"porcentaje_sd": 12.84,
			"porcentaje_min": 11.02,
			"porcentaje_max": 40.66,
			"dias_muestreados": 5
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN CARLOS",
			"porcentaje_promedio": 52.96,
			"porcentaje_sd": 8.25,
			"porcentaje_min": 42.48,
			"porcentaje_max": 64.7,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 74.44,
			"porcentaje_sd": 10.06,
			"porcentaje_min": 52.22,
			"porcentaje_max": 89.05,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 37.66,
			"porcentaje_sd": 15.76,
			"porcentaje_min": 14.36,
			"porcentaje_max": 55.53,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "cahuide",
			"porcentaje_promedio": 50.77,
			"porcentaje_sd": 5.86,
			"porcentaje_min": 43.64,
			"porcentaje_max": 59.71,
			"dias_muestreados": 6
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "12 DE ABRIL",
			"porcentaje_promedio": 0.53,
			"porcentaje_sd": null,
			"porcentaje_min": 0.53,
			"porcentaje_max": 0.53,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.43,
			"porcentaje_sd": null,
			"porcentaje_min": 0.43,
			"porcentaje_max": 0.43,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "PAUJIL",
			"porcentaje_promedio": 1.36,
			"porcentaje_sd": null,
			"porcentaje_min": 1.36,
			"porcentaje_max": 1.36,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "QUISTOCOCHA",
			"porcentaje_promedio": 0.27,
			"porcentaje_sd": null,
			"porcentaje_min": 0.27,
			"porcentaje_max": 0.27,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "SAN LUCAS",
			"porcentaje_promedio": 0.78,
			"porcentaje_sd": 0.86,
			"porcentaje_min": 0.17,
			"porcentaje_max": 2.05,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "ZUNGAROCOCHA",
			"porcentaje_promedio": 0.55,
			"porcentaje_sd": 0.38,
			"porcentaje_min": 0.22,
			"porcentaje_max": 1.0,
			"dias_muestreados": 4
		},
		{
			"ciclo_hidrologico": "Vaciante",
			"temporada_base": 2023,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "cahuide",
			"porcentaje_promedio": 1.32,
			"porcentaje_sd": 2.01,
			"porcentaje_min": 0.16,
			"porcentaje_max": 3.64,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 1.67,
			"porcentaje_sd": 2.58,
			"porcentaje_min": 0.16,
			"porcentaje_max": 4.64,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.97,
			"porcentaje_sd": 0.66,
			"porcentaje_min": 0.2,
			"porcentaje_max": 2.25,
			"dias_muestreados": 10
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 9.78,
			"porcentaje_sd": 8.62,
			"porcentaje_min": 1.85,
			"porcentaje_max": 28.49,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 20.13,
			"porcentaje_sd": 7.19,
			"porcentaje_min": 9.17,
			"porcentaje_max": 34.72,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 15.37,
			"porcentaje_sd": 7.78,
			"porcentaje_min": 1.08,
			"porcentaje_max": 25.13,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 16.31,
			"porcentaje_sd": 4.0,
			"porcentaje_min": 10.57,
			"porcentaje_max": 21.36,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 74.11,
			"porcentaje_sd": 3.64,
			"porcentaje_min": 70.43,
			"porcentaje_max": 79.93,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 62.41,
			"porcentaje_sd": 7.43,
			"porcentaje_min": 51.32,
			"porcentaje_max": 75.23,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.43,
			"porcentaje_sd": 0.1,
			"porcentaje_min": 0.36,
			"porcentaje_max": 0.49,
			"dias_muestreados": 2
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Amanecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.95,
			"porcentaje_sd": 1.11,
			"porcentaje_min": 0.17,
			"porcentaje_max": 2.22,
			"dias_muestreados": 3
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.81,
			"porcentaje_sd": 0.69,
			"porcentaje_min": 0.16,
			"porcentaje_max": 2.04,
			"dias_muestreados": 8
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Anfibio",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 3.88,
			"porcentaje_sd": 3.32,
			"porcentaje_min": 0.22,
			"porcentaje_max": 9.78,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 13.07,
			"porcentaje_sd": 4.58,
			"porcentaje_min": 5.17,
			"porcentaje_max": 19.49,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Antropogénico",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 25.58,
			"porcentaje_sd": 11.64,
			"porcentaje_min": 10.46,
			"porcentaje_max": 47.16,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 3.96,
			"porcentaje_sd": 1.86,
			"porcentaje_min": 0.73,
			"porcentaje_max": 7.32,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Ave",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 8.64,
			"porcentaje_sd": 3.5,
			"porcentaje_min": 2.21,
			"porcentaje_max": 14.39,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 82.23,
			"porcentaje_sd": 5.78,
			"porcentaje_min": 75.1,
			"porcentaje_max": 91.51,
			"dias_muestreados": 9
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Insecto",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 61.67,
			"porcentaje_sd": 7.65,
			"porcentaje_min": 47.38,
			"porcentaje_max": 68.97,
			"dias_muestreados": 11
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "23 DE FEBRERO",
			"porcentaje_promedio": 0.18,
			"porcentaje_sd": null,
			"porcentaje_min": 0.18,
			"porcentaje_max": 0.18,
			"dias_muestreados": 1
		},
		{
			"ciclo_hidrologico": "Creciente",
			"temporada_base": 2022,
			"periodo_analisis": "Anochecer Crítico",
			"categoria": "Mamífero",
			"comunidad": "VARILLAL",
			"porcentaje_promedio": 0.64,
			"porcentaje_sd": 0.44,
			"porcentaje_min": 0.22,
			"porcentaje_max": 1.25,
			"dias_muestreados": 4
		}
	]
}
'''
# --- CARGA DE DATOS ---
# (Asegúrate de que json_data contenga el string completo)
data = json.loads(json_data)
df_iph = pd.DataFrame(data['rows'])

# Aplicar traducciones para consistencia con el Dashboard
df_iph['categoria'] = df_iph['categoria'].map(CAT_TRANS).fillna(df_iph['categoria'])
df_iph['periodo_analisis'] = df_iph['periodo_analisis'].map(PERIOD_TRANS).fillna(df_iph['periodo_analisis'])
df_iph['comunidad'] = df_iph['comunidad'].str.upper()

# Erase 2022 data
df_iph = df_iph[df_iph['temporada_base'] != 2022]

# Filtrar por comunidades específicas
comunidades_validas = ['12 DE ABRIL', 'PAUJIL', 'QUISTOCOCHA', 'SAN LUCAS', 'VARILLAL']
df_iph = df_iph[df_iph['comunidad'].isin(comunidades_validas)]

# --- CONFIGURACIÓN DE REJILLA (Grid) ---
seasons = ["Creciente", "Vaciante"]
periods = ['Dawn', 'Dusk']
years = sorted(df_iph['temporada_base'].unique(), reverse=True)

output_dir = "seasonal_plots"
os.makedirs(output_dir, exist_ok=True)

for season in seasons:
    n_rows = len(years)
    n_cols = len(periods)
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(12, 5 * n_rows), sharey=True)
    
    for i, year in enumerate(years):
        for k, period in enumerate(periods):
            ax = axes[i, k] if n_rows > 1 else axes[k]
            
            data_plot = df_iph[
                (df_iph['temporada_base'] == year) & 
                (df_iph['ciclo_hidrologico'] == season) & 
                (df_iph['periodo_analisis'] == period)
            ]

            if data_plot.empty:
                ax.text(0.5, 0.5, f"No Data\n{year} {season}\n{period}", ha='center', va='center')
                continue

            sns.barplot(
                data=data_plot, 
                x='categoria', 
                y='porcentaje_promedio', 
                hue='comunidad', 
                palette=PALETTE, 
                ax=ax,
                edgecolor="black"
            )

            # Etiquetas Min-Max
            for patch, (_, row) in zip([p for p in ax.patches if p.get_height() > 0], data_plot.iterrows()):
                ax.text(
                    patch.get_x() + patch.get_width()/2, 
                    patch.get_height() + 0.5, 
                    f"[{row['porcentaje_min']}-{row['porcentaje_max']}]", 
                    ha='center', va='bottom', fontsize=7, rotation=90
                )

            ax.set_title(f"{year} {season} - {period}", fontsize=12, fontweight='bold')
            ax.set_xlabel("")
            ax.set_ylabel("% Occupation" if k == 0 else "")
            if ax.get_legend():
                ax.get_legend().remove()

    plt.tight_layout()
    save_path = os.path.join(output_dir, f"biodiversity_{season.lower()}.png")
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"Saved: {save_path}")